# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65c4d244b2ca521ff8ff5d755a641181871cd7fbc891ecc75186bc195563060b28faa01d68f1c0700f980a867b83d7e99a06e71fe2b19c8b0ba3c812b1c6a5cd

test:
  secret_key_base: fa3543d03a55076091ae92988144e84761eee14613032f8f577d62c20b51e7944994679e67a969a083c145b74cc6e03357291be73ab26d3cfc060a51ee22b343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
